steps:
  deploy:
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: SSH_HOST
      username:
        from_secret: SSH_USER
      key:
        from_secret: SSH_KEY
      port: 22
      script:
        - cd /home/ppg/frontend-kmm-next-new
        - git fetch origin
        - git reset --hard origin/main
        - docker compose down
        - docker compose build --no-cache
        - docker compose up -d
        - docker image prune -f

      # script:
      #   - cd /home/ppg/frontend-kmm-next-new
      #   - git pull origin main
      #   - docker compose down
      #   - docker compose build --no-cache
      #   - docker compose up -d
      #   - docker image prune -f
    when:
      - event: push
        branch: main
